### ISSUE TITLE
请教一下该怎么安装？

### ISSUE THREAD

**Issue by ChristianSwift** [zhaoweizhong/flarum-ext-auth-cas#1]
版本是0.1.0-beta.7

**Comment by ChristianSwift** [comment]
按您说的安装上了，但是有个问题，就是我这边的cas系统不是oath2.0，我查看了一下地址是类似于http://domain.com/cas/login?service=xxx的格式，请问这样要如何更改？

**Comment by zhaoweizhong** [comment]
我们这里既支持 OAuth 2.0 协议，也支持 CAS 协议，但是我们的信息中心推荐用 OAuth 2.0，所以我就用的是 OAuth 2.0，我这个插件也没办法经过简单修改就支持 CAS 协议。建议你咨询一下你们管理 CAS 系统的人员，问问能不能申请通过 OAuth 2.0 接入，不能的话就参考我这个花点时间自己写一个 CAS 协议的插件然后开源出来吧~还有什么问题可以继续问我
